[package]
name = "lazyprox"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.4", features = ["full"] }
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.8"
log = "0.4"
futures = "0.3"
